### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by parkeunsang** [kevin622/kevin622.github.io#1]
The screen shakes whenever pointing another tab :)

**Comment by kevin622** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ은상이 반갑

맥에서는 안 그러던데 windows 크롬에서 scrollbar가 생기는 문제 때문인 듯
지금 당장 윈도우를 쓸 수 있는 환경이 아니어서...곧 고치겠습니다

**Comment by kevin622** [comment]
7d65ee54f5d3dcfb2bc61177ca9ef29d9daad50c

요 커밋으로 고쳐질지..?

**Comment by kevin622** [comment]
The problem seems solved, so closing this issue :)

**Comment by parkeunsang** [comment]
오 굿 👍
